config/routes.rb
ThaaliyolaRor::Application.routes.draw do
  resources :reservations

  get "reports/index"
    resources :issuings

    resources :languages

    resources :languagedivisions

    resources :users

    resources :shelves

    resources :categories

    resources :shelfpositions

    resources :categorizations

    resources :authorships

    resources :authors

    resources :books

    get "list/index"
    get "books/index"
    get "reports/index"
    get "reports" => "reports#index"
    post "reports/showreport" => "reports#showreport"
    post "sign_in" => "users#sign_in"
    get "sign_in" => "users#login"
    get "success" => "users#success"
    get "sign_up" => "users#new"
    post "logout" => "users#sign_out"
    post "books/:id/reserve_book" => "reservations#reserve_book", as: "reserve_book"
    post "users/:id/reset_password" => "users#reset_password"
    get "users/:id/reset_password" => "users#password_reset", as:"password_reset"
    get "edit_user_photo" => "users#changephoto"
    patch "users/:id/issue" => "users#issue", as:"issue"
    patch "users/:id/renew" => "users#renew", as:"renew"
    patch "users/:id/return" => "users#return", as:"return"
    patch "users/:id/reset_password" => "users#reset_password"
    root :to => "books#index"

end

app/models/book.rb
class Book < ActiveRecord::Base
    has_many :authorships
    has_many :authors, through: :authorships
    accepts_nested_attributes_for :authors

    has_many :categorizations
    has_many :categories, through: :categorizations
    accepts_nested_attributes_for :categories

    has_many :issuings
    has_many :users, through: :issuings
    accepts_nested_attributes_for :users
    belongs_to :language, :dependent => :destroy

    has_many :reservations
    has_attached_file :cover
    validates_attachment_content_type :cover, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/controllers/books_controller.rb
# encoding: UTF-8
class BooksController < ApplicationController
    require 'will_paginate/array'
    rescue_from ActiveRecord::RecordNotFound, :with => :not_found
    def not_found
        render :template=>"/error/404_book.html.erb", :status=>404
    end

    before_action :set_book, only: [:show, :edit, :update, :destroy, :reserve_book]

    helper_method :current_user
    helper_method :isadmin
    # GET /books
    # GET /books.json
    def index        
        if params.has_key?(:contains)
            @books = Book.where("name LIKE ?", "%#{params[:contains]}%").uniq_by(&:bookunique).paginate(page: params[:page], per_page: 5)
        else
            @books=Book.all.uniq_by(&:bookunique).paginate(page: params[:page], per_page: 20)
        end
    end

    # GET /books/1
    # GET /books/1.json
    def show
        @copies = Book.where("bookunique = ?",@book.bookunique)
        @uniquecopies = 0
        @copies.each do |b|
            if b.users.empty?
                @uniquecopies += 1
            end
        end
        @user = current_user()

    end


    # GET /books/new
    def new
        @book = Book.new
        @book.authors.build
        @book.categories.build
        @book.users.build
    end

    # GET /books/1/edit
    def edit
    end

    # POST /books
    # POST /books.json
    def create
        @language = params[:book][:language][:name]
        @language_exist = Language.where("name = ?",@language.to_s)
        if @language_exist.empty?
            @language_created=Language.new(:name=>@language.to_s)
            @book=@language_created.books.build(book_params)
            @language_created.save
        else
            @book=Book.new(book_params)
            @book.language=@language_exist.first
        end

        @authors = params[:book][:author][:name].to_s.split(";")
        @categories = params[:book][:category][:name].to_s.split(";")
        respond_to do |format|
            if @book.save
                @authors.each do |author|
                    @author_exist=Author.where("name = ?",author.to_s)

                    if @author_exist.empty?
                        @author_created=@book.authors.create(:name=>author.to_s)
                        @author_created.save
                    else
                        @book.authors<<@author_exist
                    end
                end
                @categories.each do |category|
                    @category_exist = Category.where("name = ?",category.to_s)
                    if @category_exist.empty?
                        @category_created=@book.categories.create(:name=>category.to_s)
                        @category_created.save
                    else
                        @book.categories<<@category_exist.first
                    end
                end
                unique = params[:book][:name].to_s + params[:book][:author][:name].to_s + params[:book][:category][:name].to_s
                @book.bookunique = unique
                @book.save
                noofcopies = params[:book][:noofcopies]
                puts "Unique is "
                puts unique
                puts "Number of copies is"
                puts noofcopies
                counter=0
                while counter < noofcopies.to_i - 1
                    @newbook = @book.dup
                    @newbook.authors=@book.authors
                    @newbook.categories=@book.categories
                    @newbook.save
                    counter = counter + 1
                end

                format.html { redirect_to @book,notice:"Book Succesfully Created",debugnotice:@debugnotice}
                format.json { render action: 'show', status: :created, location: @book }
            else
                format.html { render action: 'new' }
                format.json { render json: @book.errors, status: :unprocessable_entity }
            end
        end
    end

    def reserve_book
        @user = current_user()
        Reservation.create(:book => @book, :user => @user)
        respond_to do |format|
            notice="Book Requested. You'll be notified when it becomes available"
            format.html { redirect_to @book,notice:notice}
        end

    end


    # PATCH/PUT /books/1
    # PATCH/PUT /books/1.json
    def update
        @authors = params[:book][:author][:name].to_s.split(";")
        if params[:book][:author][:name]!=""
            Authorship.where(:book_id=>@book.id).each do |auth|
                auth.delete
            end
        else
            params[:book].delete(:author)
        end
        @authors.each do |author|
            @author_exist=Author.where("name = ?",author.to_s)

            if @author_exist.empty?
                @author_created=@book.authors.create(:name=>author.to_s)
                @author_created.save
            else
                @book.authors<<@author_exist
            end
        end
        @categories = params[:book][:category][:name].to_s.split(";")
        if params[:book][:category][:name]!=""
            Categorization.where(:book_id=>@book.id).each do |cat|
                cat.delete
            end
        else
            params[:book].delete(:category)
        end
        @categories.each do |category|
            @category_exist = Category.where("name = ?",category.to_s)
            if @category_exist.empty?
                @category_created=@book.categories.create(:name=>category.to_s)
                @category_created.save
            else
                @book.categories<<@category_exist.first
            end
        end

        respond_to do |format|
            if @book.update(book_params)
                format.html { redirect_to @book, notice: 'Book was successfully updated' }
                format.json { head :no_content }
            else
                format.html { render action: 'edit' }
                format.json { render json: @book.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /books/1
    # DELETE /books/1.json
    def destroy
        @str=""
        @book.authors.each do |a|
            if a.books.count == 1
                a.destroy
            end
        end
        @book.destroy
        respond_to do |format|
            format.html { redirect_to books_path,notice: @str }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
        @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
        params.require(:book).permit(:serial, :name,:author,:category, :shelf, :row, :language, :id, :cover,:noofcopies)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.haml
= form_for(@book, class:"form-signin") do |f|
  - if @book.errors.any?
    #error_explanation
      %h2
        = pluralize(@book.errors.count,"error") 
        prohibited this book from being saved.
      %ul
        - @book.errors.full_messages.each do |msg|
          %li= msg
  = f.text_field :serial, class: "form-control", placeholder: "Serial"
  = f.text_field :name, class: "form-control", placeholder: "Name"
  = f.fields_for :author do |author_form|
    =author_form.text_field :name, class: "form-control", placeholder: "Authors (Use ';' to split)"
  - @cat = Category.all
  - @catlist = Array.new
  - @cat.each do |c|
    - @catlist << c.name
  = f.fields_for :category do |category_form|
    = category_form.text_field :name, class: "form-control", style: "display:none"
  %select.multiselect{:multiple=> true}
    %option{value: 'aana'} Aana
    %option{value: 'tomatoes'} Tomatoes
  = f.text_field :shelf, class: "form-control", placeholder: "Shelf"
  = f.text_field :row, class: "form-control", placeholder: "Row"
  = f.text_field :noofcopies, class: "form-control", placeholder: "Number of Copies"
  = f.fields_for :language do |language_form|
    = language_form.text_field :name, class: "form-control", placeholder: "Language"
  = f.file_field :cover,class: "btn", title:"Choose Profile Pic"
  = button_tag 'Submit', src:books_path, class:"btn btn-primary", style:"width:100%"
:javascript
  $(document).ready(function() {
  $('.multiselect').multiselect({});});

app/views/books/edit.haml
%h1{style:"text-align:center"} 
  Edit
  =@book.name
= render 'form'

app/views/books/index.haml
.centeredtext
  - if params.has_key?(:contains)
    %h1= t('books_under',:query => params[:contains].to_s)
  - else
    %h1= t('all_books')
  = will_paginate @books, renderer: BootstrapPagination::Rails
%table.table.table-hover{"width" => "100%"}
  %tr
    %th.col-md-6 Book
    %th.col-md-6 Author
  - @counter = 1
  - @books.each do |book|
    %tr
      %td
        = link_to book.name, book
      - if book.authors.empty?
        %td
      - else
        %td
          - book.authors.each do |author|
            = link_to author.name,author
            %br

app/views/books/new.haml
%h1{"style" => "text-align:center"} Add New Book
= render 'form'

app/views/books/show.haml
.jumbotron{style:"margin-top:5%;padding-top:1px"}
  .row


    #left{style:"width:75%;float:left"}
      %h1= @book.name
      %p
        - @book.authors.each do |author|
          = link_to author.name,author
          - if not author.equal? @book.authors.last
            ;
      - @book.categories.each do |category|
        %p= link_to category.name, category
      %p
        Row :
        = @book.row
      %p
        Shelf :
        = @book.shelf
      %p
        Total Number of Copies : 
        = @copies.count
      %p
        Number of Copies Available : 
        = @uniquecopies
      - if isadmin()
        = button_to 'Edit Details', edit_book_path,{method:"get",class:"btn btn-lg btn-primary", style:"float:left;margin-right:5%;margin-top:5%"}
        = button_to 'Delete Book', @book,{method:"delete",class:"btn btn-lg btn-danger", style:"float:left;margin-right:5%;margin-top:5%", confirm:"Are you sure?"}
      - if @user != nil and isadmin()==false
        = button_to 'Reserve Books', reserve_book_path(:book=>@book,:user=>@user), method:"post", class:"btn btn-lg btn-primary"


    #right{style:"float:left;margin-top:5%"}
      - if @book.cover.file?
        = image_tag @book.cover.url,{style:"width:125px;height:160px"}
      - else
        = image_tag "passport_sample.png"
%table.table.table-bordered
  %tr
    %th Book Id
    %th User Name
    %th Date of Issue
    %th Date of Return
  - @copies.each do |b|
    - Issuing.where("book_id = ? ",b.id).each do |i|
      %tr
        %td= b.id
        %td= User.find(i.user_id).name
        %td= i.dateofissue
        %td= i.dateofreturn