config/routes.rb
ThaaliyolaRor::Application.routes.draw do
  resources :reservations

  get "reports/index"
    resources :issuings

    resources :languages

    resources :languagedivisions

    resources :users

    resources :shelves

    resources :categories

    resources :shelfpositions

    resources :categorizations

    resources :authorships

    resources :authors

    resources :books

    get "list/index"
    get "books/index"
    get "reports/index"
    get "reports" => "reports#index"
    post "reports/showreport" => "reports#showreport"
    post "sign_in" => "users#sign_in"
    get "sign_in" => "users#login"
    get "success" => "users#success"
    get "sign_up" => "users#new"
    post "logout" => "users#sign_out"
    post "books/:id/reserve_book" => "reservations#reserve_book", as: "reserve_book"
    post "users/:id/reset_password" => "users#reset_password"
    get "users/:id/reset_password" => "users#password_reset", as:"password_reset"
    get "edit_user_photo" => "users#changephoto"
    patch "users/:id/issue" => "users#issue", as:"issue"
    patch "users/:id/renew" => "users#renew", as:"renew"
    patch "users/:id/return" => "users#return", as:"return"
    patch "users/:id/reset_password" => "users#reset_password"
    root :to => "books#index"

end

app/models/author.rb
class Author < ActiveRecord::Base
    has_many :authorships
    has_many :books, through: :authorships, :dependent => :destroy
    accepts_nested_attributes_for :books
    has_attached_file :photo
    validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
   
end

app/models/authorship.rb
class Authorship < ActiveRecord::Base
    belongs_to :book
    belongs_to :author
end

app/models/book.rb
class Book < ActiveRecord::Base
    has_many :authorships
    has_many :authors, through: :authorships
    accepts_nested_attributes_for :authors

    has_many :categorizations
    has_many :categories, through: :categorizations
    accepts_nested_attributes_for :categories

    has_many :issuings
    has_many :users, through: :issuings
    accepts_nested_attributes_for :users
    belongs_to :language, :dependent => :destroy

    has_many :reservations
    has_attached_file :cover
    validates_attachment_content_type :cover, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
    belongs_to :book
    belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :categorizations
    has_many :books , through: :categorizations
    accepts_nested_attributes_for :books
end

app/models/issuing.rb
class Issuing < ActiveRecord::Base
    belongs_to :book
    belongs_to :user
end

app/models/language.rb
class Language < ActiveRecord::Base
    has_many :books
    accepts_nested_attributes_for :books
end

app/models/languagedivision.rb
class Languagedivision < ActiveRecord::Base
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
    belongs_to :user
    belongs_to :book
end

app/models/shelf.rb
class Shelf < ActiveRecord::Base
end

app/models/shelfposition.rb
class Shelfposition < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :issuings
    has_many :books, through: :issuings
    accepts_nested_attributes_for :books
    validates :username, uniqueness: true
    validates_confirmation_of :password, :message => "Passwords must match"
    validates_presence_of :password_confirmation, :if => :password_changed?
    has_many :reservations
    has_attached_file :profpic
    validates_attachment_content_type :profpic, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
#    before_save :encrypt_password
    #def encrypt_password
        #puts "Current Password" + self.password
        #self.password = Digest::SHA1.hexdigest(self.password)
    #end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/issuings_helper.rb
module IssuingsHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/shelves_helper.rb
module ShelvesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_leftsidebar.haml
#sidebar-wrapper
  %ul.sidebar-nav
    %li.sidebar-brand
      %b= link_to t('thaaliyola'), books_path
    %li= link_to t('sidebar.books'), books_path
    %li= link_to t('sidebar.authors'), authors_path
    %li= link_to t('sidebar.categories'), categories_path
    %li= link_to t('sidebar.languages'), languages_path
    %li
      .form-group
        %input.form-control#searchquery{type:"text",placeholder:"#{t('sidebar.search_query')}",style:"margin-left:5%;width:90%"}
      .btn.btn-group{style:"width:100%"}
        %button.btn.dropdown-toggle.form-control{"type" => "button","data-toggle" => "dropdown"}
          = t('sidebar.search_in')
          %span.caret
        %ul.dropdown-menu.formcontrol{role:"menu",style:"padding:0;border-radius:2px;width:90%;margin-left:5%"}
          %li
            %a.searchmenu#search{href:"",onclick:"searchbook()"}= t('sidebar.books')
          %li
            %a.searchmenu#search{href:"",onclick:"searchauthor()"}= t('sidebar.authors')
          %li
            %a.searchmenu#search{href:"",onclick:"searchcategory()"}= t('sidebar.categories')

app/views/layouts/_rightsidebar.haml
- currentuser = current_user()
#sidebar-wrapper-right
  %ul.sidebar-nav{style:"margin-left:5%;width:90%"}
    - if currentuser.nil?
      #centered{style:"text-align:center"}
        %p 
          = render 'users/formsignin'
          %br
          Not a member?
          %br
          Register
          = link_to "Here", sign_up_path
    - else
      %h2{style:"color:white"}
        = link_to currentuser.username,currentuser
        = button_to t('sidebar.logout'),logout_path,class:"btn"
    - if isadmin()
      .input-group
        %input.form-control#userid{type:"text",placeholder:"Admission Number"}
        %span.input-group-btn
          %button.btn{onclick:"gotouser()"}
            Go
      %li= link_to "Add Book", new_book_path
      %li= link_to "Add User", new_user_path

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title= t('thaaliyola')
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = favicon_link_tag
  %body
    #wrapper
      = render ('layouts/rightsidebar')
      = render ('layouts/leftsidebar')
      #page-content-wrapper
        .content-header{style:"padding:0 0 0 0;margin:0 0 0 0"}
        %a#menu-toggle.btn.btn-default{href:"#"}
          %i.icon-reorder
        - if signinnotice(" ") != ""
          - if $successmessage.include?(notice)
            .alert.alert-success.alert-dismissable
              %button.close{"type" => "button","data-dismiss" => "alert","aria-hidden" => "true"} &times;
              = notice
          - elsif $failuremessage.include?(notice)
            .alert.alert-danger.alert-dismissable
              %button.close{"type" => "button","data-dismiss" => "alert","aria-hidden" => "true"} &times;
              = notice
        = yield  

:javascript
  $("#menu-toggle").click(function(e){
  e.preventDefault();
  $("#wrapper").toggleClass("active");
  });